services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-app
    container_name: ecommerce-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - ecommerce-network

  webserver:
    image: httpd:alpine
    container_name: ecommerce-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    networks:
      - ecommerce-network
    depends_on:
      - app

  database:
    image: mysql:8.0
    container_name: ecommerce-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ecommerce-network
    ports:
      - "3307:3306"

volumes:
  dbdata:

networks:
  ecommerce-network:
    driver: bridge